# Generated by Django 5.2.4 on 2025-09-15 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateMetricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('pie_chart', models.CharField(choices=[('project', 'Project'), ('category', 'Category'), ('chain', 'Chain')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baserow_id', models.PositiveIntegerField(unique=True, verbose_name='Baserow ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AggregateMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('format', models.CharField(choices=[('{:,.2f}', 'Comma separated, 2 decimal places'), ('{:,.0f}', 'Comma separated, no decimals')], max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('chart', models.BooleanField(default=False)),
                ('pie_chart', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dashboard.aggregatemetrictype')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='DB ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('format', models.CharField(choices=[('{:,.2f}', 'Comma separated, 2 decimal places'), ('{:,.0f}', 'Comma separated, no decimals')], max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('current_value_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('plastic', 'Plastic'), ('solar', 'Solar'), ('carbon', 'Carbon'), ('biodiversity', 'Biodiversity'), ('cookstove', 'Cookstove')], max_length=20, null=True)),
                ('aggregate_metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.aggregatemetric')),
                ('projects', models.ManyToManyField(related_name='metrics', to='dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMetricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateTimeField(db_index=True)),
                ('project_metrics', models.ManyToManyField(related_name='metric_data', to='dashboard.projectmetric')),
            ],
            options={
                'verbose_name': 'Project Metric Data',
                'verbose_name_plural': 'Project Metric Data',
                'indexes': [models.Index(fields=['date'], name='dashboard_p_date_8f5d29_idx')],
            },
        ),
    ]
