# Generated by Django 5.2.4 on 2025-09-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(db_index=True, editable=False, max_length=64, unique=True),
        ),
    ]
