# Generated by Django 5.2.4 on 2025-09-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_apikey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatemetrictype',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
