# Generated by Django 5.2.4 on 2025-09-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_aggregatemetrictype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
