# Generated by Django 5.2.4 on 2025-10-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='impact_json',
            field=models.JSONField(blank=True, help_text='Optional Impact Metrics JSON for this project', null=True),
        ),
    ]
