# Generated by Django 5.2.4 on 2025-10-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_project_impact_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
