# Generated by Django 5.2.4 on 2025-11-17 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_project_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='aggregatemetric',
            name='sdg',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sdgs_aggregate', to='dashboard.sdg'),
        ),
        migrations.AddField(
            model_name='projectmetric',
            name='sdg',
            field=models.ForeignKey(
                db_constraint=False,  # temporarily disable FK constraint
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sdgs_project',
                null=True,
                default=None,
                to='dashboard.sdg',
            ),
        ),
    ]

