# Generated by Django 5.2.4 on 2025-11-25 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_sdg_aggregatemetric_sdg_projectmetric_sdg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatemetric',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dashboard.aggregatemetrictype'),
        ),
        migrations.AlterField(
            model_name='projectmetric',
            name='sdg',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sdgs_project', to='dashboard.sdg'),
        ),
    ]
