# Generated by Django 5.2.4 on 2025-11-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_aggregatemetric_type_alter_projectmetric_sdg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatemetric',
            name='sdg',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sdgs_aggregate', to='dashboard.sdg'),
        ),
        migrations.AlterField(
            model_name='aggregatemetric',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='dashboard.aggregatemetrictype'),
        ),
    ]
