# Generated by Django 5.2.4 on 2025-12-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_aggregatemetric_sdg_alter_aggregatemetric_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatemetric',
            name='sdg_chart',
            field=models.BooleanField(default=False),
        ),
    ]
